.github/workflows/be-ci.yaml, .github/workflows/deploy.yaml, .github/workflows/fe-ci.yaml, docker-compose.yml, server/src/configs/typeorm.config.ts
- be, fe CI 설정 추가
- dev 브랜치 push할 때 
- /client/*, /server/* 중 변경 있는 쪽만 테스트 실행
- docker-compose 설정 변경으로 typeorm.config 임시 설정 삭제
- fe 빌드 커맨드와 테스트 커멘드를 확인해주세요.
=> [Feature-8-5] CI/CD 설정 추가

client/src/App.css, client/src/components/MainSection/ControlSection/ListView/index.tsx, client/src/components/MainSection/ControlSection/index.tsx, client/src/components/MainSection/index.tsx, client/src/components/MindMapView/index.tsx, client/src/components/Sidebar/Overview.tsx, client/src/components/Sidebar/index.tsx, client/src/index.css, client/src/pages/Main/index.tsx
- 캔버스의 사이즈 조정 로직 추가
- 스타일 오류 수정
- mainsection 높이가 넘어가는 문제 수정
- Listview 스크롤이 제대로 작동이 되지 않는 스타일 문제 수정
- body를 벗어나는 메인 영역 요소들,,
- 현재는 container를 두고 height를 90%로 설정하여 문제는 해결됐지만 조금 더 개선이 필요해 보임
=> [Feature-1-fix] - 스타일 충돌 및 오류 수정

client/src/components/MainSection/ControlSection/ListView/NodeList.tsx, client/src/components/MainSection/ControlSection/ListView/index.tsx
- 데이터 구조 변경 ( 트리 구조 -> 객체 구조 )에 따른 ListView 컴포넌트 수정
=> [Feature-4-1] 서버에서 JSON 데이터가 오면 클라이언트는 이를 파싱하여 List Element로 변환한다.

client/src/components/MainSection/ControlSection/ListView/NodeList.tsx
- NodeList안 data -> nodeData 변경 ( list 쪽 에러 )
=> [Feature-4-1-fix-fe] NodeList안 data -> nodeData로 변경 (에러 수정)

Dockerfile.nginx, api-server/src/configs/typeorm.config.ts, api-server/src/modules/connection/connection.controller.ts, api-server/src/modules/connection/connection.service.ts, socket-server/.prettierrc, socket-server/src/app.module.ts, socket-server/src/configs/typeorm.config.ts, socket-server/src/exceptionfilter/ws.exceptionFilter.ts, socket-server/src/main.ts, socket-server/src/middlewares/logger.middleware.ts, socket-server/src/modules/map/entity/mindmap.entity.ts, socket-server/src/modules/map/entity/node.entity.ts, socket-server/src/modules/map/entity/user.entity.ts, socket-server/src/modules/map/exceptions/exception.ts, socket-server/src/modules/map/map.gateway.ts, socket-server/src/modules/map/map.service.ts, socket-server/src/pipes/mindmap.validation.pipe.ts, socket-server/src/pipes/ws.validation.pipe.ts
- 노드 관련 로직 변경 
- 기존 : 
- 생성, 삭제 수정 개별적으로 작동
- 변경
- 생성, 삭제 요청 -> 성공 시 update 요청 다시 보내는거로 수정
- 로거 미들웨어 추가
- ValidationPipe 추가
- ExceptionFilter 추가
=> [Feature-3-11-fix] 노드 추가, 삭제, 수정 로직 변경

.github/workflows/deploy.yaml, socket-server/src/modules/map/dto/mindmap.update.dto.ts, socket-server/src/modules/map/dto/node.delete.dto.ts, socket-server/src/modules/map/exceptions/exception.ts, socket-server/src/modules/map/map.gateway.ts, socket-server/src/modules/map/map.service.ts
- 노드 생성 시 생성된 노드 보내도록 수정
- 노드 삭제 여러개 한번에 할 수 있도록 수정
- 소켓 연결시 현재 redis에 저장된 데이터 전송 추가
=> [Feature-3-11-fix-be] 노드 생성, 삭제 로직 수정 && 소켓 연결시 현재 데이터 전송 추가

api-server/package-lock.json, api-server/package.json, api-server/src/app.module.ts, api-server/src/interface/authenticated.request.interface.ts, api-server/src/interface/index.ts, api-server/src/modules/auth/auth.controller.ts, api-server/src/modules/auth/auth.module.ts, api-server/src/modules/auth/strategies/github.strategy.ts, api-server/src/modules/auth/strategies/kakao.strategy.ts, api-server/src/modules/connection/connection.controller.ts, api-server/src/modules/connection/connection.module.ts, api-server/src/modules/connection/connection.service.ts, api-server/src/modules/user/dto/index.ts, api-server/src/modules/user/dto/user.create.dto.ts, api-server/src/modules/user/dto/user.info.dto.ts, api-server/src/modules/user/entities/user.entity.ts, api-server/src/modules/user/user.controller.ts, api-server/src/modules/user/user.module.ts, api-server/src/modules/user/user.service.ts, socket-server/package-lock.json, socket-server/package.json, socket-server/src/app.module.ts, socket-server/src/modules/map/entity/user.entity.ts
- OAuth 받아오는 정보에 이름 추가
- 모듈 import 미작성 수정
=> [Feature-7-1-be- fix] 모듈 임포트 수정 및 OAuth 받아오는 정보 추가

.gitignore, Docker-compose.dev.yml, Dockerfile.api-server.dev, Dockerfile.fe.dev, Dockerfile.nginx.dev, Dockerfile.socket-server.dev, client/vite.config.ts, nginx/dev.conf
- Docker-compose.dev.yml 실행하면 됩니다.
- .env.dev 는 프로젝트 root 경로에 만들어주세요.
=> [feature-0] 도커 개발환경 추가

client/src/components/Minutes/Tiptap/MenuBar.tsx, client/src/components/Minutes/Tiptap/index.tsx, client/src/components/Minutes/Tiptap/styles.css, client/src/konva_mindmap/components/EditableText.tsx
1. 버튼을 두 번 눌러야 적용되는 현상 수정 ( MenuBar 롤백 )
2. 드래그 하고 다른 영역 선택 시 드래그가 유지되는 현상 수정
1. https://luxurious-share-af6.notion.site/tiptap-style-8aa203f6a67148999cfc1b3f7369da52
2. https://luxurious-share-af6.notion.site/tiptap-a7a4818fb7be413eab03b9493000429b
=> [Feature-8-3-fix-fe] 회의록 관련 에러 수정 & 버튼 이미지 수정

client/package.json, client/src/components/MindMapCanvas/ShowShortCut.tsx, client/src/components/MindMapCanvas/index.tsx, client/src/konva_mindmap/components/MindMapNode.tsx, client/src/store/NodeListProvider.tsx
- 에러 수정
- 중복선언들 수정
- 단축키 UI 수정
- socket 삭제한 부분 남아있는 것 다시 삭제
=> [Dev-fe-fix] dev 머지 후 충돌 & 에러들 수정

client/src/konva_mindmap/events/addNode.ts, client/src/konva_mindmap/hooks/useAdjustedStage.ts, client/src/konva_mindmap/utils/vector.ts
- 수직 벡터 구하는 함수 -> 원하는 길이와, 각도를 주입해 원하는 벡터를 리턴해주는 함수로 변경
- 초기 비율 1로 고정 -> 최대 1.5 최소 0.5로 비율이 보여지게 수정
- 노드 첫 생성 위치가 고정되게 생성이 됨 -> 루트 노드와의 위치를 확인 후 적당한 위치에 생성되도록 수정
=> [Feature-3-17-fe] 벡터 함수 수정 & 초기 비율 수정 & 노드 첫 생성 위치 수정

client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx, client/src/hooks/useNodeActions.ts
#117 리스트에서 이루어지는 모든 조작은 소켓 통신을 통해 다른 이용자들에게 공유된다.
소켓 관련 이벤트 함수들 리스트 뷰에 모두 연결해놨습니다.
=> [feature-4-10-fe] 리스트에서 이루어지는 모든 조작은 소켓 통신을 통해 다른 이용자들에게 공유된다.

client/src/components/Dashboard/MindMapInfoItem.tsx, client/src/components/Dashboard/index.tsx, client/src/components/DeleteMindMapModal/index.tsx, client/src/components/MindMapCanvas/CanvasButtons.tsx, client/src/components/MindMapCanvas/ShowShortCut.tsx, client/src/components/MindMapHeader/MindMapHeaderButtons.tsx, client/src/components/Minutes/Tiptap/index.tsx, client/src/components/Minutes/index.tsx, client/src/components/ShareModal/index.tsx, client/src/components/common/Modal.tsx
- share 모달 추가
- 전체 모달들 통일
- 회의록 관련 에러 수정
=> [Feature-jjambbong3-fe] share 모달 추가 & 전체 모달들 통일 & 회의록 관련 에러 수정

client/package-lock.json, client/src/store/NodeListProvider.tsx
- 서버 로직 반영해서 joinRoom에서 데이터 꺼내는 방식 변경
- 기존에는 joinRoom 이벤트에서 nodeData 자체를 통째로 보내 주었는데, 이제 해당 값이 nodeData라는 key의 value로 들어오게 되어 프론트엔드에서도 이를 기반으로 setData하도록 만들었습니다.
- package-lock.json 복구
=> [Feature-3-7-fix-fe] 변경된 서버 로직과 프론트엔드 초기 데이터 불러오는 방식 동기화 / package-lock.json 복구

client/src/api/index.ts, client/src/components/Dashboard/UserDashBoard.tsx, client/src/components/LoginModal/index.tsx, client/src/components/MindMapCanvas/ToolMenu.tsx, client/src/components/MindMapMainSection/index.tsx, client/src/hooks/useAuth.ts, client/src/store/NodeListProvider.tsx, client/src/store/useAuthStore.ts, client/src/store/useSocketStore.ts, client/src/utils/localstorage.ts, client/src/utils/token.ts
#126 비회원 유저는 새로운 마인드맵 누르기를 누르면 유저 권한의 마인드맵이 생성되고 회의록 권한은 해당 유저만 사용이 가능하다.
- 비회원 유저가 마인드맵이 만들 시 로컬스토리지에 owner key값으로 배열에 마인드맵 Id를 넣을 수 있도록 함
- connection을 하는 과정에서 마인드맵id를 context api에 등록하여 이를 통해 joinRoom이 이루어진 후에 유저 권한을 설정할 수 있도록 추가
=> [Feature-0-5-fe] 비회원 유저는 새로운 마인드맵 누르기를 누르면 유저 권한의 마인드맵이 생성되고 회의록 권한은 해당 유저만 사용이 가능하다.

.gitignore, client/src/components/MindMapHeader/Profile.tsx, client/src/konva_mindmap/components/MindMapNode.tsx
다른 노드들을 클릭했을 때 그룹 선택한 노드가 아니면 그룹 해제를 할 수 있도록 수정했습니다.
=> HOTFIX : 그룹을 선택하고 다른 노드를 클릭했을 때 그룹 선택한 노드들이 딸려오는 에러 해결

client/src/pages/layout/index.tsx, client/src/store/useSocketStore.ts
- 소켓 연결 요청 url 변경
- 서버에서 namespace를 지웠다고 해서 반영했습니다
- useSocketStore에 소켓의 연결 상태를 나타내는 connectionStatus 추가
- 해당 값에 따라 네트워크 경고 alert나 연결 오류 페이지를 띄워 줄 예정입니다.
- 지금은 해당 에러가 네트워크 끊김 상태일 때 발생하는 에러다 보니 NotFound 페이지의 이미지가 깨져서 보이는데... 해결하면 주석 풀겠습니다. 마음대로 잘 되지 않아 일단 주석 걸고 올립니다 ㅠㅠ
=> [feature-3-7-fix-fe] io 객체 생성 url 변경 / connection 상태에 따라 비정상적인 연결 해제시 에러 페이지 표시

.github/workflows/deploy.yaml, BE/Dockerfile.api, BE/Dockerfile.socket, BE/apps/api-server/src/app.module.ts, BE/apps/socket-server/src/app.module.ts, docker-compose.yml, nginx/default.conf
=> [Feature-0-fix] 배포 설정 변경

BE/Dockerfile.api, BE/Dockerfile.socket
=> [feature-0-fix] fix : 도커파일 빌드 커맨드 수정

client/src/components/Dashboard/GuestDashBoard.tsx, client/src/components/Dashboard/NoMindMap.tsx, client/src/components/LoginModal/index.tsx
=> [Feature-0-3-fix-fe] 대시보드 UI 수정 & 로그인 모달 UI 수정

BE/Dockerfile.api, BE/Dockerfile.socket
=> fix : 수정된 Dockerfile에서 nest build 명령어를 npx로 변경

BE/apps/api-server/src/modules/mindmap/mindmap.service.ts, BE/apps/socket-server/src/main.ts, BE/apps/socket-server/src/modules/map/map.gateway.ts, BE/apps/socket-server/src/modules/map/map.service.ts, docker-compose.yml
- 소켓 글로벌 예외필터 적용
- 오타 수정 및 guest 검증 로직 수정
=> [Feature-0-fix] 배포 버그 수정

BE/apps/api-server/src/modules/connection/connection.service.ts, BE/apps/api-server/src/modules/dashboard/dashboard.service.ts, BE/apps/api-server/src/modules/user/user.service.ts, BE/apps/socket-server/src/guard/ws.jwt.auth.guard.ts, BE/apps/socket-server/src/modules/map/map.service.ts
- getInfo api userId 추가
- dashboard api owner -> ownerName, ownerId 변경
- jwt 수정
=> [deploy-be-fix] 소켓 jwt 가드 수정 및 user api 수정

client/src/main.tsx
=> chore : 로그인 데이터 검사

client/src/components/MindMapMainSection/index.tsx, client/src/hooks/useAuth.ts, client/src/pages/layout/index.tsx, client/src/store/useSocketStore.ts
- 토큰이 있을 경우 auth에 담아서, 아닐 경우 빼서 io 객체를 생성하도록 변경했습니다.
- 캔버스 영역에서 화면을 새로고침할 때
- '새로운 마인드맵 만들기' 버튼을 눌렀을 때
=> [Feature-3-7-fix-fe]

BE/apps/api-server/src/app.module.ts, BE/apps/api-server/src/exceptionFilter/http.exception.filter.ts, BE/apps/api-server/src/exceptions/exception.ts, BE/apps/api-server/src/exceptions/index.ts, BE/apps/api-server/src/main.ts, BE/apps/api-server/src/middlewares/token.refresh.middleware.ts, BE/apps/api-server/src/modules/auth/auth.service.ts, BE/apps/api-server/src/modules/connection/connection.service.ts, BE/apps/api-server/src/modules/dashboard/dashboard.service.ts, BE/apps/api-server/src/modules/mindmap/mindmap.service.ts, BE/apps/api-server/src/modules/node/node.service.ts, BE/apps/api-server/src/modules/pubsub/subscriber.service.ts, BE/apps/socket-server/src/guard/ws.jwt.auth.guard.ts, BE/apps/socket-server/src/modules/map/map.gateway.ts, BE/libs/entity/src/node.entity.ts
=> [Feature-0-fix] 배포 오류 수정

client/src/components/Dashboard/GuestDashBoard.tsx, client/src/components/Dashboard/GuestNewMindMapModal.tsx, client/src/components/Dashboard/MindMapInfoItem.tsx, client/src/components/Dashboard/NoMindMap.tsx, client/src/components/Dashboard/UserDashBoard.tsx, client/src/components/DeleteMindMapModal/index.tsx, client/src/components/LoginModal/index.tsx, client/src/components/MindMapCanvas/CanvasButtons.tsx, client/src/components/MindMapCanvas/DeleteConfirmModal.tsx, client/src/components/MindMapCanvas/NoNodeInform.tsx, client/src/components/MindMapHeader/MindMapHeaderButtons.tsx, client/src/components/MindMapHeader/ProfileModal.tsx, client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx, client/src/components/MindMapMainSection/ControlSection/UploadBox.tsx, client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx, client/src/components/common/NotFound.tsx
- 모달 hover 효과 통일
- png -> react-icons 변경
=> [Feature-modal-fe] 모달 hover 효과 통일 & png -> react-icons 변경

BE/apps/api-server/src/main.ts, BE/apps/socket-server/src/modules/map/map.service.ts, docker-compose.yml
=> fix : redis에 연결 정보 없을 때 등록하도록 수정

client/src/components/Minutes/index.tsx
=> [Feature-minutes-fix-fe] 회의록 z-index 수정

BE/apps/api-server/src/app.module.ts, BE/apps/api-server/src/exceptionFilter/http.exception.filter.ts, BE/apps/api-server/src/middlewares/token.refresh.middleware.ts, BE/apps/api-server/src/modules/node/node.service.ts, BE/apps/socket-server/src/exceptionfilter/ws.exceptionFilter.ts, BE/libs/entity/src/node.entity.ts
=> fix : 리프레시 미들웨어 제거, 마인드맵 삭제 로직 수정

client/src/components/Minutes/Tiptap/index.tsx, client/src/store/NodeListProvider.tsx
- 회의록 실시간 데이터 반영
- 제목 변경시 실시간 데이터 반영
현재 updateTitle에 대한 응답으로 updateContent 이벤트가 오는 문제가 있습니다. 수정하면 좋을 것 같습니다 !
=> [Feature-socket-fix-fe] 회의록, 제목 관련 실시간 데이터 반영

client/src/components/MindMapCanvas/CanvasButtons.tsx, client/src/konva_mindmap/events/deleteNode.ts
- 루트 노드 삭제 방지
- 루트 노드가 포함되어 있을 경우 리턴
- 노드 초기화시 루트노드 제외 모두 삭제
=> [feature-socket-fix-fe] 루트 노드 삭제 방지

client/src/store/useSocketStore.ts
- connectSocket에서 기존에 있던 소켓이 있으면 중복 연결되는 것을 방지하던 if문을 지워버려 복구했습니다
=> [feature-socket-fix-fe] 실수로 지운 로직 복구

client/src/components/MindMapCanvas/ShowShortCut.tsx, client/src/components/ShareModal/index.tsx, client/src/main.tsx, client/src/pages/TestPage.tsx
- aitest 페이지 추가
- 단축키 창 토글 모드 추가
- 공유 모달창 링크 복사 버튼 수정
=> [Feature-aitest-fe] aitest 페이지 & 단축키 창 토글 모드 추가

client/src/components/Minutes/Tiptap/index.tsx, client/src/components/Minutes/Tiptap/styles.css, client/src/components/Minutes/Tiptap/utils/indent.ts
- 회의록 들여쓰기 내어쓰기 안되던 오류 수정
- list도 들여쓰기 내어쓰기 되도록
=> [Feature-minutes-fix2-fe] 회의록 들여쓰기 내어쓰기 안되던 오류 수정 & list도 들여쓰기 내어쓰기 되도록

client/src/components/MindMapCanvas/index.tsx, client/src/konva_mindmap/components/MindMapNode.tsx, client/src/konva_mindmap/hooks/useCollisionDetectionForWorker.ts, client/src/konva_mindmap/utils/collision-worker.ts, client/src/store/useConnectionStore.ts
- 기존의 충돌 방지 기능이 쓰로틀링을 적용했더라도 노드가 많아질 수록 프레임 드랍이 일어났었습니다.
- 이에 Web Worker에게 충돌 방지 확인 로직을 위임하는 방식으로 리팩토링 해보았습니다.
- 현재는 실험적인 기능으로, 파일은 추가됐지만 로직은 바뀌지 않았습니다.
- 혹시 몰라 일단 추가만 해두려고 합니다..
=> [Feature-3-8-fe-refactor] ⚠️Experimental : Web worker를 사용한 충돌 방지 기능 리팩토링

BE/apps/api-server/src/modules/ai/ai.service.ts, BE/apps/api-server/src/modules/connection/connection.service.ts, BE/apps/api-server/src/modules/mindmap/mindmap.service.ts, BE/apps/api-server/src/modules/node/node.service.ts, BE/apps/api-server/src/modules/subscriber/subscriber.service.ts, BE/apps/socket-server/src/modules/map/map.gateway.ts, BE/apps/socket-server/src/modules/map/map.service.ts, BE/apps/socket-server/src/modules/subscriber/subscriber.service.ts
- 마인드맵 생성시 연결 정보 저장
- api서버, 소켓서버 같은 이벤트 수신하고 있던거 수정
- room에 있는 사용자에게 aiResponse 보내는 로직 수정
- 게스트 ai요청 막음
=> [Feature-2-be-fix] AI 요청 오류 수정

client/src/store/NodeListProvider.tsx, client/src/store/createSocketSlice.ts
- handleConnection 방식 변경 및 socketSlice 클린업 함수를 추가하여 중복 이벤트 처리를 막았습니다.
=> [feature-socket-fix] refactor : handleConnection 방식 변경 및 socketSlice 클린업 함수 추가

client/src/components/MindMapCanvas/index.tsx, client/src/konva_mindmap/components/DrawMindMap.tsx, client/src/konva_mindmap/components/EditableText.tsx, client/src/konva_mindmap/components/EditableTextInput.tsx, client/src/konva_mindmap/components/MindMapNode.tsx, client/src/konva_mindmap/events/addNode.ts, client/src/types/Node.ts
- scale에 따른 Text, input 크기 확대 혹은 축소
- addNode 에러 수정
=> [Feature-scale-fe] scale에 따른 Text, input 창 크기 조정 & addNode 에러 수정

client/src/api/ai.api.ts, client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx, client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx, client/src/constants/uploadLimit.ts
- ai 요청이 timeout으로 인해 네트워크에서 에러로 표시되는 문제를 해결했습니다.
- 오디오 파일 전송 로직에서 에러를 캐치하면 로딩 상태가 풀리도록 개선했습니다.
- 글자수 제한을 변경했습니다.
=> [Feature-dev-hotfix] ai 요청 hotfix

BE/apps/api-server/src/modules/ai/ai.controller.ts, BE/apps/api-server/src/modules/subscriber/subscriber.service.ts, BE/apps/socket-server/src/modules/map/map.gateway.ts, BE/apps/socket-server/src/modules/map/map.service.ts
=> [Feature-5-be-fix]ai 요청 오류시 pending 상태 해제

client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx, client/src/components/MindMapMainSection/ControlSection/VoiceFileUpload.tsx, client/src/hooks/useUpload.ts
- 비회원은 AI 변환 서비스를  사용할 수 없도록 막아두었습니다.
=> [feature-dev-hotfix] 비회원 AI 변환 블락

client/src/store/NodeListProvider.tsx, client/src/store/createSocketSlice.ts
=> [feature-historyState-fix] ai 요청시 history가 초기화되게 설정

BE/apps/api-server/src/modules/connection/dto/connection.query.dto.ts
- connection 쿼리 dto @IsString에서 mindmapId를 못받고 있는 문제 수정
=> [feature-5-be-fix] dto 수정

client/index.html, client/src/konva_mindmap/utils/nodeAttrs.ts
- html lang en -> ko
- 노드 사이 선 위치 수정
=> [Feature-html-fe] html lang en -> ko & 노드 사이 선 위치 수정

client/src/api/auth.api.ts
무한으로 refresh와 logout이 지속되던 문제가 있어 refresh와 logout에 대한 인터셉터를 따로 설정하여 오류가 발생했을 경우 클라이언트단에서 로그아웃 되도록 개선했습니다.
=> [feature-dev-hotfix] HOTFIX : 무한으로 refresh와 logout이 지속되던 문제 해결

BE/apps/api-server/src/modules/auth/auth.controller.ts, BE/apps/api-server/src/modules/auth/auth.service.ts, BE/apps/api-server/src/modules/connection/dto/connection.query.dto.ts, BE/apps/api-server/src/strategies/kakao.strategy.ts, BE/apps/socket-server/src/modules/map/map.gateway.ts, BE/apps/socket-server/src/modules/map/map.service.ts
- connection dto 검증 로직 수정 (connection 403 에러 수정)
- 데이터 저장 시점 변경  ( room의 인원이 0명일 때 -> 사용자가 연결 끊길 때 마다)
- 로그아웃 jwt 가드 제거
- room에 남아있는 인원 없을 때 redis 데이터 만료 설정
=> [Feature-be-fix] 6주차 배포 오류 수정

client/src/components/Minutes/Tiptap/index.tsx, client/src/store/NodeListProvider.tsx
- 회의록에서 커서 무단 이동 문제 해결
- ai 요청도 history에 저장되도록 변경
=> [Feature-minutes-fix] 회의록에서 커서 무단 이동 문제 해결 / ai 요청도 history에 저장되도록 변경

client/src/components/MindMapCanvas/index.tsx
=> [Feature-key-fix-fe]case문 안 break 추가

client/src/store/createSocketSlice.ts
- 사용자가 방에서 나갈 경우 nodeError가 비워지도록 설정
=> [feature-socket-fix] 사용자가 방에서 나갈 경우 nodeError가 비워지도록 설정

client/src/components/Dashboard/MindMapInfoItem.tsx, client/src/components/Dashboard/UserDashBoard.tsx, client/src/components/Modal/ShareModal.tsx
=> [Feature-dashboard-fe] 대시보드 정렬 기능 추가

client/src/api/auth.api.ts, client/src/api/index.ts
=> [feature-dev-hotfix] logout 중복 호출 문제 해결
