- client/src/components/MindMapView/index.tsx
- client/src/hooks/useHistoryState.ts
- client/src/hooks/useWindowKeyEventListener.ts
- client/src/store/NodeListProvider.tsx
- client/src/types/Node.ts
#25 
- 특정 상태의 history를 관리할 수 있도록 만들어 줍니다.
- `undo` 함수를 통해 이전 상태로 돌아갈 수 있고, `redo` 함수를 통해 앞으로 가기 기능을 사용할 수 있습니다.
- window에 KeyBoard 관련 이벤트를 정의할 수 있습니다. 이벤트 종류(string)와 핸들러 함수를 전달하면 전역에 등록해 줍니다.
지금은 `useHistoryState`로 관리되는 상태가 업데이트되면 바로 history에 저장되고 있는데, 리팩토링을 통해 history에 상태 저장을 트리거하는 함수를 따로 두어야 합니다. (ex. 유저가 요소를 드래그하고 있을 때 매번 상태가 변경이 되는데, 이를 모두 history에 저장하지 않고 유저가 드래그 액션을 끝냈을 때 해당 값만 history에 등록되도록) 해당 작업은 다른 로직들과의 통합 이후에 진행하도록 하겠습니다.
> [Feature-3-4] 유저는 마인드맵에 있는 개별 요소를 클릭하고 아래 삭제 버튼을 통해 삭제할 수 있다.

- client/src/components/MindMapView/index.tsx
- client/src/konva_mindmap/events/ratioSizing.ts
- client/src/konva_mindmap/node.tsx
[#68](https://github.com/boostcampwm-2024/web32-BooMap/issues/68)
작업 내용
해당 PR은 3-8-fe 머지 이후에 머지 바랍니당
* 마인드맵 확대 및 축소를 마인드맵 위에 커서를 두고 휠을 돌리면 가능하도록 이벤트 구현 및 핸들러 등록
* 마인드맵의 stage에 draggable 속성을 주어 드래그 앤 드롭으로 마인드맵 포커스 변경
논의하고 싶은 내용
> [Feature-3-10-fe] 유저는 마인드맵을 확대, 축소 시키거나 드래그 앤 드랍으로 포커스를 바꿀 수 있다.

- client/package-lock.json
- client/package.json
- client/src/konva_mindmap/EditableText.tsx
- client/src/konva_mindmap/EditableTextInput.tsx
- client/src/konva_mindmap/node.tsx
#30 
https://github.com/user-attachments/assets/f175d893-2367-4e32-a57d-a38dbce097f8
- `react-konva-utils`를 설치했습니다. [레포링크](https://github.com/konvajs/react-konva-utils)
- canvas 위에서 간단하게 html 요소를 사용할 수 있게 해 줍니다. 저는 input을 쓰기 위해 설치했습니다.
- 마인드맵의 요소 (원 또는 텍스트)를 더블클릭할 경우, 해당 텍스트가 input으로 변경됩니다.
- 이를 위해 `EditableText`, `EditableTextInput` 두 가지 컴포넌트를 정의했습니다.
- `EditableText`는 `isEditing` 여부에 따라 input이나 `Text`를 보여 줍니다
- `EditableTextInput`은 input을 사용하여 사용자의 입력을 받고 변경사항을 감지합니다
- 요소를 input으로 만들어 수정한 다음, 엔터키를 누르거나 해당 input 외부 영역을 클릭하면 변경사항이 반영됩니다.
- 이때 input 안에 내용이 없을 경우 input이 비활성화되지 않고, 빨간색 테두리가 생기도록 했습니다.
- 영상에도 들어가 있지만 input이 활성화되면 텍스트의 위치가 좌측 위쪽으로 이동합니다. `EditableTextInput`에게 `offset` 값이 전달되지 않아서 발생하는 문제인데, `EditableTextInput`에서 `groupProps`로 `offset` 값을 줘 봐도 어째서인지 잘 동작하지 않았습니다... (시도했던 코드는 아래 …
> [Feature-3-5-fe] 유저는 마인드맵에 있는 개별 요소를 더블클릭을 하면 수정할 수 있다.

- client/src/components/Header/index.tsx
- client/src/components/MainSection/ControlSection/ListView/NodeItem.tsx
- client/src/components/MainSection/ControlSection/ListView/NodeList.tsx
- client/src/components/MainSection/ControlSection/ListView/index.tsx
- client/src/components/MindMapView/CanvasButtons.tsx
- client/src/components/MindMapView/DeleteConfirmModal.tsx
- client/src/components/MindMapView/NoNodeInform.tsx
- client/src/components/MindMapView/ToolMenu.tsx
- client/src/components/MindMapView/index.tsx
- client/src/constants/color.ts
- client/src/hooks/useHistoryState.ts
- client/src/hooks/useNodeActions.ts
- client/src/konva_mindmap/components/DrawMindMap.tsx
- client/src/konva_mindmap/components/EditableText.tsx
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/konva_mindmap/components/NewNode.tsx
- client/src/konva_mindmap/events/addNode.ts
- client/src/konva_mindmap/events/deleteNode.ts
- client/src/konva_mindmap/events/ratioSizing.ts
- client/src/konva_mindmap/hooks/useCollisionDetection.ts
- client/src/konva_mindmap/hooks/useDimension.ts
- client/src/konva_mindmap/utils/collision.ts
- client/src/konva_mindmap/utils/download.ts
- client/src/konva_mindmap/utils/following.ts
- client/src/store/NodeListProvider.tsx
- client/src/store/useStageStore.ts
- client/src/types/Node.ts
- 새로운 노드를 추가할 때 생길 노드를 따로 구분하여 추가되도록 하였습니다.
- showNewNode를 통해 상태에 newNode property가 붙어있는 노드를 추가하고, 편집이 완료되면 addNode를 통해 노드의 플래그를 바꿔주어 실제 다른 노드를과 상호작용하는 노드로 바꿀 수 있습니다.
- 캔버스 비우기를 눌렀을 때, 확인 모달이 뜨고 '초기화할게요'버튼을 누르면 캔버스가 초기화되도록 변경했습니다.
- 캔버스 모달의 경우 react-portal을 사용해서 body 태그에서 렌더링될 수 있도록 구현했습니다.
- 하나의 노드를 끌어당길 때, 일정 길이 이상 나가게 된다면 부모가 움직이는 방향에 따라 자식 노드가 따라갈 수 있도록 로직을 구현했습니다.
- 각각의 자식 노드들은 드래그가 시작될 때, 부모 노드에 대한 자식 노드의 offset을 map 자료구조에 저장하고, 드래그가 끝난 후에는 다시 해당 map에서 각 노드들의 상대적 위치 정보를 가져와 업데이트 할 수 있도록 했습니다.
[노드가 따라가게 하기 기술공유 노션 링크](https://luxurious-share-af6.notion.site/1417725fa9ac8060944ec3769d9056a8?pvs=4)
- addNode했을 때의 리스트 뷰 로직이 제가 리팩토링했던 부분과 달라 협의 후 조정되었습니다.
- node 타입의 경로를 변경하면서 import문들의 경로 또한 변경했습니다.
- 캔버스 재정렬 및 비우기 버튼 컴포넌트가 로직이 추가되면서 가독성이 떨어지는 문제가 생겨 mindmapView에서 분리할 필요가 있다 판단하여 컴포넌트 …
> [Feature-3-jjambbong2] 노드 조작 관련 기능 결합 및 신규 기능 추가

- client/src/components/Dashboard/GuestDashBoard.tsx
- client/src/components/MindMapCanvas/CanvasButtons.tsx
- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/MindMapCanvas/index.tsx
- client/src/components/MindMapMainSection/index.tsx
- client/src/components/Sidebar/Overview.tsx
- client/src/hooks/useHistoryState.ts
- client/src/konva_mindmap/components/EditableText.tsx
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/konva_mindmap/components/NewNode.tsx
- client/src/konva_mindmap/events/addNode.ts
- client/src/konva_mindmap/events/deleteNode.ts
- client/src/store/NodeListProvider.tsx
- client/src/store/SocketSlice.ts
- client/src/store/useSocketStore.ts
#35 
- 노드 초기화를 할 때 (`resetAllNode`), `deleteNode` 이벤트가 아니라 `updateNode`를 보내도록 변경 (서버 로직과 동기화)
- 노드 재정렬 버튼을 눌렀을 때, 재정렬된 위치를 담아 `updateNode` 이벤트를 발생시키도록 변경
- 사이드바의 버튼들을 눌렀을 때 소켓 연결이 열리도록 변경
- 연결이 없으면 새로 만들고, 있을 경우 viewMode만 바꿉니다
- `useHistoryState`에서, `pointer`가 0일 때도 `undo`가 불가능하도록 변경 (원래는 -1까지 갈 수 있어서 에러가 났음)
- `updateNode` 이벤트 중복 등록으로 인한 `saveHistory` 중복 호출 및 history 꼬임 문제 해결
- `socketSlice`에 정의되어 있는 `handleSocketEvent`로 소켓 호출을 통일하여, 이벤트 해지 및 등록을 일관되게 관리
- `deleteNode`는 추후 변경 예정입니다 (현재 로직 수정 중이라고 들었습니다)
- `socketSlice` -> `useSocketStore` 이름 변경
- 슬라이스 패턴을 사용할 것이라 생각해서 이렇게 이름을 지어뒀지만... 아니라서 수정했습니다
> [feature-3-7-fix-fe] 누락된 소켓 연결 시나리오 추가 및 이벤트 리스너 중복 부착으로 인한 history 문제 해결

- client/src/components/Dashboard/UserDashBoard.tsx
- client/src/components/MindMapCanvas/index.tsx
- client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
- client/src/components/MindMapMainSection/ControlSection/index.tsx
- client/src/components/MindMapMainSection/index.tsx
- client/src/konva_mindmap/components/EditableText.tsx
- client/src/konva_mindmap/components/EditableTextInput.tsx
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/konva_mindmap/components/NewNode.tsx
- client/src/store/NodeListProvider.tsx
- client/src/types/Node.ts
노드 추가 Input창이 포커싱이 리스트 뷰에서만 포커싱이 되는 문제를 해결했습니다.
문제의 원인은 리스트 뷰와 캔버스 모두에서 각각 autofocusing을 준 데다가, 리스트 뷰의 경우 useEffect ref까지 걸어 focus를 통해 포커싱을 유도하여 마인드맵에서 노드를 추가해도 포커싱이 리스트 뷰로 옮겨갔습니다
이를 해결하기 위해 각 노드를 선택하고 추가할 때, 어떤 항목에서 노드가 추가되는지를 상태에 기록하고 이에 따라 포커싱을 줄 수 있도록 수정했습니다.
> [Feature-3-6-fix-fe] 노드 추가 Input창 포커싱 관련 문제

- client/src/hooks/useNodeActions.ts
- client/src/konva_mindmap/components/EditableText.tsx
- 화면상 동기화를 위한 `editableText`의 `useEffect` 롤백
- 노드 수정시 원래 content와 내용이 동일할 경우 요청 전송 방지
https://github.com/user-attachments/assets/33644db3-49ab-4396-893c-660b34cda74a
> [feature-3-7-fix-fe] 노드 수정시 원래 content와 동일할 경우 요청 전송 방지

- client/src/api/dashboard.api.ts
- client/src/api/fetchHooks/useDashBoard.ts
- client/src/api/fetchHooks/useDeleteMindMap.ts
- client/src/api/mindmap.api.ts
- client/src/components/Dashboard/MindMapInfoItem.tsx
- client/src/components/Dashboard/NoMindMap.tsx
- client/src/components/Dashboard/UserDashBoard.tsx
- client/src/components/MindMapHeader/index.tsx
- client/src/components/Minutes/Tiptap/index.tsx
- client/src/konva_mindmap/types/dashboard.ts
이슈번호 : #21 #23 #26 
- 대시보드에서 대시보드 가져오는 api와 이를 호출하여 데이터를 가져오거나 mutate하는 쿼리 훅을 추가했습니다.
- 쿼리 훅같은 경우 기존에 사용하는 훅들보다 사용할 수 있는 환경이 한정적인 점을 고려하여 api에 추가적으로 fetchHooks라는 디렉토리를 만들어 따로 보관하였습니다.
```tsx
export function useDeleteMindMap({ mindMapId, onError }) {
const queryClient = useQueryClient();
return useMutation({
mutationFn: () => deleteMindMap(mindMapId),
mutationKey: ["dashboard"],
onSuccess: () => queryClient.invalidateQueries({ queryKey: ["dashboard"] }),
onError,
});
}
```
- useMutation 훅의 경우는 기존의 API를 사용해서 CRUD 중 CUD들에 대한 작업을 주로 수행하는데, 요청이 완료되면 queryclient에서 기존에 가지고 있던 캐시를 비활성화시키면서 다시금 fetch가 이루어질 수 있도록 하였습니다.
- 에러의 경우 훅을 사용하는 컴포넌트 내부에서 사용할 수 있도록 하였습니다.
- 대시보드가 없을 때 띄울 화면을 추가했습니다.
- 대시보드에서 마인드맵을 누르면 해당 마인드맵으로 navigate하여 연결될 수 있도록 하였습니다.
- 그 밖에 추가적인 사항으로 비회원 유저의 경우 제목 수정을 막아놓는 기능을 추가했습니다. …
> [Feature-6-1,2-fe] 유저는 기존에 생성했던 마인드맵 히스토리를 눌러 해당 마인드맵 캔버스로 이동할 수 있다.

- client/src/components/Dashboard/MindMapInfoItem.tsx
- client/src/components/Sidebar/LatestMindMapModal.tsx
- client/src/components/Sidebar/Overview.tsx
- client/src/store/NodeListProvider.tsx
- client/src/utils/localstorage.ts
#130 대시보드에 있을 때, 기존 작업 내역이 있는 경우 사이드바의 다른 버튼들을 누르면 최근 방문했던 마인드맵으로 돌아가기와 새로운 마인드맵 누르기 버튼이 모달로 생기며 두 가지 선택지를 통해 마인드맵에 접근할 수 있다.
- 기존 작업을 하고 소켓 연결이 끊겼을 때, 로컬스토리지에 최근 마인드맵 정보를 저장하고 대시보드에서 다시 사이드바를 통해 마인드맵 생성을 누르면 최근 방문했던 마인드맵으로 돌아가기와 새로운 마인드맵 누르기 버튼을 가지는 모달이 켜지도록 했습니다.
- 대시보드에서 키워드가 없을 때와 있을 때의 heigth가 차이가 나서 통일될 수 있도록 높이를 조정했습니다.
```tsx
const navigateMindmap = (mode: "listview" | "voiceupload" | "textupload") => {
if (socket) {
handleViewMode(mode);
return;
}
const latestMindMap = getLatestMindMap();
if (!latestMindMap) {
handleConnection(navigate, mode, isAuthenticated);
}
openModal();
};
function navigateToLatestMindap() {
navigate(`/mindmap/${getLatestMindMap()}?mode=listview`);
closeModal();
}
function navigateToNewMindMap() {
handleConnection(navigate, "listview", isAuthenticated); …
```
> [Feature-6-10-fe]대시보드에 있을 때, 기존 작업 내역이 있는 경우 사이드바의 다른 버튼들을 누르면 최근 방문했던 마인드맵으로 돌아가기와 새로운 마인드맵 누르기 버튼이 모달로 생기며 두 가지 선택지를 통해 마인드맵에 접근할 수 있다.

- client/src/components/Dashboard/GuestDashBoard.tsx
- client/src/components/MindMapHeader/index.tsx
- client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
- client/src/components/Minutes/Tiptap/index.tsx
- client/src/components/Minutes/index.tsx
- client/src/components/Sidebar/Overview.tsx
- client/src/components/Sidebar/OverviewButton.tsx
- client/src/hooks/useContent.ts
- client/src/hooks/useMindMapTitle.ts
- client/src/konva_mindmap/utils/throttle.ts
- client/src/store/NodeListProvider.tsx
- client/src/store/useSocketStore.ts
- client/src/types/NodePayload.ts
#132 소유자는 헤더의 마인드맵 제목이나 회의록의 내용을 변경할 수 있으며, 변경 내용은 broadcast되어 동시 편집중인 모든 사람들에게 보인다.
- 제목과 회의록에 소켓 이벤트를 부착하고, broadcast될 때 다른 사용자들 또한 변경사항이 반영될 수 있도록 변경했습니다.
- 로그인 유저가 마인드맵 상태에서 새로고침 했을 때, 다시금 토큰을 refresh 하고 이에 따른 사용자 권한을 검사할 수 있도록 로직을 추가했습니다.
- 제목의 경우 제대로 소켓 이벤트가 가지 않으면 기존의 값으로 롤백될 수 있도록 하였습니다.
- 회의록 소켓 이벤트의 경우에는 쓰로틀링을 활용하여 1.5초마다 한번씩 회의록 본문을 소켓으로 보낼 수 있도록 하였습니다.
- nodeListProvider에 제목과 회의록을 위한 커스텀 훅을 별도로 분리하여 해당 훅에서 실행할 수 있도록 하였습니다./
NodeListProvider가 이전 노드만의 데이터를 다룰 때에는 적당한 네이밍이라고 생각했지만, 해당 마인드맵의 정보를 모두 관리하게 되면서 사이즈가 점점 커지고 이를 보다 커스텀 훅으로 각각의 역할을 분리하는 것이 좋을 것 같다는 생각이 듭니다.
추가적으로 비단 노드만의 데이터를 관리한다기에는 이제는 마인드맵 데이터의 전체를 관리하는 context api가 되었기 때문에 네이밍도 변경할 필요성이 있어 보입니다.
> [Feature-3-19-fe] 소유자는 헤더의 마인드맵 제목이나 회의록의 내용을 변경할 수 있으며, 변경 내용은 broadcast되어 동시 편집중인 모든 사람들에게 보인다.

- client/src/components/DeleteMindMapModal/index.tsx
- client/src/components/MindMapCanvas/CanvasButtons.tsx
- client/src/components/MindMapCanvas/DeleteConfirmModal.tsx
- client/src/components/MindMapCanvas/ShowShortCut.tsx
- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/MindMapCanvas/index.tsx
- client/src/components/ShareModal/index.tsx
- client/src/konva_mindmap/components/EditableTextInput.tsx
- client/src/konva_mindmap/components/NewNode.tsx
- client/src/konva_mindmap/events/addNode.ts
- client/src/konva_mindmap/hooks/useAdjustedStage.ts
- client/src/konva_mindmap/hooks/useDimension.ts
- client/src/konva_mindmap/utils/initializeNodePosition.ts
- client/src/konva_mindmap/utils/nodeAttrs.ts
- 마인드맵 재정렬 로직
- 마인드맵 재정렬 시 영역 가운대로 위치 이동
- 모달 UI 수정 & 통일
- ToolBar UI 수정 & hover 수정
- input 크기 조정
1. 마인드맵에서 드래그만 한 상태에서 재정렬을 누르게 되면 dimension에서 변경사항이 없기 때문에 가운대로 위치 이동이 되지 않는데 이 부분이 잘 안되고 있습니다ㅜㅜ 여러 시도들을 해봤는데 잘 안되네요..
2. 마인드맵 초기 영역 비율이 처음부터 끝까지 계속 유지가 되다 보니 새로고침을 하기 전까지는 계속 비율이 일정한 상태에서 재정렬이 돌게 되네요.. 그래서 의존성 배열에 data를 넣자니 data가 변경될때마다 함수가 일어나게 되서 일단은 빼놨는데.. 어떻게 해야될까요ㅜㅜ
그리고 노드가 영역 바깥 쪽에서 생성되었을 때 input에 focus가 일어나면서 캔버스 영역의 이동이 일어나는데 이 부분도 해결해야 될 것 같습니다ㅜㅜ
> [Feature-3-2-fix-fe] 마인드맵 재정렬 로직 수정 & 모달 UI 통일 &

- client/src/api/mindmap.api.ts
- client/src/components/Dashboard/MindMapInfoItem.tsx
- client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
- client/src/components/Sidebar/Overview.tsx
- client/src/store/useAuthStore.ts
- client/src/store/useSocketStore.ts
- 대시보드에서 마인드맵으로 이동했을 경우 기존에 있었던 navigate 로직을 제거하고 api 요청 후에 소켓 연결을 하고, 이후 이동을 할 수 있도록 로직을 보완했습니다.
- 최근 이동했던 마인드맵이 없을 경우에도 모달이 뜨던 문제를 수정했습니다.
> [Feature-6-9-fe-fix] 대시보드에서 마인드맵 이동시 api 호출과 소켓 연결 후 이동 보완

- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/Sidebar/Overview.tsx
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/konva_mindmap/components/NodeTool.tsx
- client/src/konva_mindmap/components/selectionRect.tsx
- client/src/konva_mindmap/utils/nodeAttrs.ts
- client/src/types/Node.ts
#156 마인드맵을 클릭하면 노드 위에 툴을 통해서도 수정, 삭제, 추가가 가능하다 
- 마인드맵 선택 시 노드 위에 툴들이 뜰 수 있도록 하여 사용작가 보다 편하게 이용할 수 있도록 하였습니다.
- 마인드맵 안의 요소가 캔버스 바깥을 나갔음에도 보이는 문제를 해결했습니다.
- 확대와 축소 버튼의 경우 한번만 클릭해도 작동할 수 있도록 개선했습니다.
마인드맵 안의 요소가 캔버스 바깥을 나갔음에도 보이는 문제를 해결했지만, 아직까지 오른쪽에서 노드를 추가했을 때는 갑자기 캔버스가 줄어드는 문제가 있었습니다. 아직 원인 파악이 안돼서 확인 중입니다...
> [Feature-3-20-fe] 마인드맵을 클릭하면 노드 위에 툴을 통해서도 수정, 삭제, 추가가 가능하다 

- client/src/components/MindMapCanvas/NoNodeInform.tsx
- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/MindMapCanvas/index.tsx
- client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
- client/src/hooks/useNodeActions.ts
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/store/NodeListProvider.tsx
- client/src/types/Node.ts
- 마인드맵에서 하던 것과 동일합니다
- 리스트 보기에서 노드 수정시 프론트엔드 상태를 업데이트하지 않고 있었습니다. updateNode 이벤트에 대한 콜백으로 넣어 뒀습니다.
- addTo 속성이 더이상 사용되지 않아 삭제하고, 이를 통해 listView의 항목들이 autofocus되지 않는 문제 (3번 클릭해야 텍스트를 입력할 수 있었던 문제)를 해결했습니다.
> [Feature-3-fix-fe] 노드를 추가했을 때 input이 아닌 상태를 default로 설정 / 자동 select 조정 및 enter시 input 활성화 (리스트 영역)

- client/src/hooks/useNodeActions.ts
https://github.com/user-attachments/assets/8ad733fd-056e-483e-9b2a-ed0c5e5c5384
- 캔버스 영역에서와 마찬가지로 처리했습니다.
> [feature-4-fix-fe] 리스트뷰에서 input이 비어있을 경우 원래 내용으로 돌아가지 않던 문제 해결

- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/MindMapCanvas/index.tsx
- client/src/components/MindMapHeader/index.tsx
- client/src/components/MindMapMainSection/ControlSection/TextUpload.tsx
- client/src/components/common/ArrowBox.tsx
- client/src/constants/textUploadLimit.ts
- client/src/hooks/useUpload.ts
- client/src/konva_mindmap/components/EditableText.tsx
- client/src/konva_mindmap/events/deleteNode.ts
- client/src/main.tsx
- client/src/pages/Mindmap/index.tsx
- client/src/store/NodeListProvider.tsx
- client/src/store/createSocketSlice.ts
- client/src/types/NodePayload.ts
이슈번호 : #12 #47 #188 변환용 텍스트파일 업로드 관련
---
- aiRequest와 response, aiPending 관련 소켓 이벤트를 추가했습니다. 아직 서버와의 테스트는 안되었기 때문에 테스트 후 조정할 필요가 있습니다.
- 소유권자가 아닐 경우, 안내 말풍선이 버튼 위로 뜰 수 있도록 하였습니다.
- 추가적으로 말풍선 컴포넌트를 만들어 containerClassName: absolute주는영역 스타일  boxClassName: 말풍선 컨테이너 영역 스타일,  arrowClassName: 말풍선의 화살표 스타일을 지정할 수 있도록 해놓았습니다.
- 최소 최대 텍스트 입력 제한 상수명을 추가 및 변경했습니다.
- Escape를 누르면 그룹 선택이 취소되고, input이 활성화된 상태이면 blur처리 될 수 있도록 하였습니다.
- 그룹 선택에서 루트 노드를 포함하고 삭제를 누르면 루트를 제외한 루트의 children들이 모두 삭제 처리될 수 있도록 하였습니다.
- 툴 메뉴의 확대 버튼 클릭 상태에서 나가게 되면 줌인이 계속되는 오류를 해결했습니다.
- 그룹을 선택하고 아래 툴 메뉴에서 삭제 버튼을 누르면 동작하지 않는 오류를 해결했습니다.
> [Feature-2-fe] 변환용 텍스트파일 업로드 및 오류수정

- client/src/components/MindMapHeader/index.tsx
- client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
- client/src/konva_mindmap/utils/findLastLeafNode.ts
- client/src/konva_mindmap/utils/findParentNodeKey.ts
- client/src/konva_mindmap/utils/moveToNode.ts
- client/src/konva_mindmap/utils/vector.ts
- client/src/types/Node.ts
- 리스트 라코디언 쪽 depth가 3까지만 적용 -> depth가 무한이여도 적용되도록 수정
- 타입 추가 & 수정
- header input 활성화 시 outline & border 롤백
- list hover시 버튼들 생기면 버튼이랑 키워드들 왼쪽으로 밀리는 현상 수정
> [Feature-list-fix-fe] 리스트 아코디언 관련 함수 확장 & 타입 추가 & 수정

- client/src/components/MindMapHeader/Profile.tsx
- client/src/components/MindMapHeader/ProfileModal.tsx
- client/src/constants/color.ts
- client/src/konva_mindmap/components/MindMapNode.tsx
- 프로필 모달을 누르면 계속 떴다가 사라지는문제를 해결했습니다.
- 프로필 모달이 활성화됐을 때, 바깥 부분 중 프로필 모달 영역은 클릭해도 작동하지 못하게 하고, 기존의 프로필 클릭 이벤트만 작동하게 하도록 하여 해결했습니다.
- 노드 색상과 테두리, 그림자 등 스타일을 변경했습니다
> [Feature-0-fe-fix] 퍼블리싱 관련 오류 해결

- client/src/api/index.ts
- client/src/components/MindMapHeader/Profile.tsx
- client/src/components/MindMapHeader/ProfileModal.tsx
- client/src/components/MindMapHeader/index.tsx
- client/src/constants/color.ts
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/main.tsx
- client/src/store/createMindMapOwnershipSlice.ts
- 소유권 관련 문제를 해결했습니다.
- react-query상에서 user/Info에 대해서 상태 업데이트시마다 구독한 콜백이 있는데, 여기서 401에러가 뜨면 로그아웃 처리가 되면서 맵이 초기화되던 문제였습니다.
- 소유권자의 경우 제목 수정 socket 이벤트가 response로 오기 때문에 이에 따른 제목과 수정 텍스트 상태를 업데이트 할 수 있도록 해주었습니다.
> [Feature-3-19-fe-fix] 소유권 관련 문제 및 제목 수정 오류 해결

- BE/apps/api-server/common/constant.ts
- BE/apps/api-server/src/modules/ai/ai.controller.spec.ts
- BE/apps/api-server/src/modules/ai/ai.controller.ts
- BE/apps/api-server/src/modules/ai/ai.module.ts
- BE/apps/api-server/src/modules/ai/ai.service.ts
- BE/apps/api-server/src/modules/auth/auth.service.ts
- BE/apps/api-server/src/modules/connection/connection.controller.ts
- BE/apps/api-server/src/modules/connection/connection.service.ts
- BE/apps/api-server/src/modules/mindmap/mindmap.service.ts
- BE/apps/api-server/src/pipes/file.validation.pipe.ts
- BE/apps/api-server/src/pipes/index.ts
- BE/apps/socket-server/src/modules/map/map.gateway.ts
- BE/apps/socket-server/src/modules/subscriber/subscriber.service.ts
- BE/package-lock.json
- BE/package.json
- nginx/default.conf
- nginx/dev.conf
- POST api/ai/audio/:mindmapId 추가
- nginx BODY 최대 사이즈 변경
- 소켓 aiPending 요청 추가
- 파일 확장자 validation 파이프 추가
---
- redis에 연결 정보가 없거나 잘못된 연결ID로 연결시 connectionId로 redis 데이터 캐싱
> [Feature-5-be] 텍스트 AI 요청 에러처리 추가 및 audio 파일 전송 api 추가

- BE/apps/api-server/src/modules/ai/ai.service.ts
- BE/apps/socket-server/src/modules/map/map.gateway.ts
- BE/apps/socket-server/src/modules/map/map.service.ts
- 클라이언트에서 막고있지만 서버에서도 aiCount 검증
- aiCount 감소 로직을 ai 처리 과정에서 오류가 나지 않았을 때 감소하도록 변경
> [Feature-5-be-fix] aiCount 검증 추가 및 감소 로직 response로 이동

- client/src/hooks/useHistoryState.ts
> [feature-historyState-fix] history에 빈 객체가 있을 경우 접근 방지

- BE/apps/api-server/src/modules/connection/connection.controller.ts
- BE/apps/api-server/src/modules/connection/connection.service.ts
> [Feature-be-fix] get Connection 403 에러 로그 추가, 게스트 마인드맵 생성 기본값 추가

- client/src/api/index.ts
- client/src/store/createAuthSlice.ts
- client/src/store/createSharedSlice.ts
- client/src/store/createSocketSlice.ts
- client/src/utils/formData.ts
- 오디오 파일을 전송 시 한국어가 포함된 파일이름일 경우, formData에서는 UTF-8 인코딩이 없으면 제대로 보내지지 않는다는 사실을 알게 되었습니다.
- 따라서 `encodeURIComponent`를 통해서 파일 이름을 인코딩 후, 새로운 파일 객체에 담아 formData에 넣어주었습니다.
- 서버에서는 인코딩된 파일 이름을 디코딩하는 작업이 필요할 것 같습니다.
- 로그인 시 무효화된 토큰의 경우 로그아웃 후 새로고침을 통해 로딩 모달이 계속되던 문제를 해결했습니다.
> [Feature-dev-hotfix] 인코딩 문제 및 로그인 문제 해결

- client/src/store/NodeListProvider.tsx
- client/src/store/createSocketSlice.ts
이런 문제가 있었습니다.
```
A랑 B 창을 열고, 같은 링크에서 작업
A가 노드를 조작하고, B의 화면에 내용이 반영이 됨
그 다음에 B가 노드를 조작하면 A의 화면에 반영이 안 됨
그 이후 A나 B가 노드를 조작하면 둘 다 자기 화면에만 반영이 됨
```
`handleSocketEvent`에서 `off`를 할 때 모든 리스너가 사라져 서버의 response를 상시로 listen해야 하는 리스너까지 함께 사라지기 때문에 발생하는 문제임을 파악했습니다. 해당 부분 수정하여 올립니다
> [Feature-socket-fix] 소켓이 잘못된 핸들러를 없애 이벤트 수신 및 반영이 안 되던 문제 해결

- client/src/components/Dashboard/MindMapInfoItem.tsx
- client/src/components/Dashboard/UserDashBoard.tsx
- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/MindMapHeader/index.tsx
- client/src/components/Minutes/Tiptap/index.tsx
- client/src/components/common/Toast/ToastContainer.tsx
- client/src/constants/color.ts
- client/src/konva_mindmap/events/addNode.ts
- client/src/konva_mindmap/utils/getNewNodePosition.ts
- client/src/konva_mindmap/utils/initializeNodePosition.ts
- 노드 재정렬 로직 수정
- 노드 생성 위치 로직 수정
- 노드 색상 변경
- z-index 수정
- 소유자 width 길이 수정
- 제목 최대 길이 수정
- tiptap placeholder 텍스트 수정
> [Feature-position-refactor-fe] 노드 재정렬 로직 수정 & 노드 생성 위치 로직 수정 & 노드 색상 변경

- client/src/components/MindMapCanvas/ToolMenu.tsx
- client/src/components/MindMapCanvas/index.tsx
- client/src/konva_mindmap/components/MindMapNode.tsx
- client/src/store/NodeListProvider.tsx
- redo를 할 때 undo가 함께 트리거되던 문제 해결
- 그룹 선택 이동시 매번 history 갱신 되던 문제 해결
어제 리팩토링을 하면서 `overrideNodeData`에 `saveHistory`를 넣었는데, 그룹 선택 후 `handleDragMove`를 할 때 해당 함수를 사용하고 있어서 발생한 문제였습니다.
> [Feature-historyState-fix] redo를 할 때 undo가 함께 트리거되던 문제 해결 / 그룹 선택 이동시 매번 history 갱신 되던 문제 해결

- client/src/components/MindMapHeader/index.tsx
- client/src/components/MindMapMainSection/ControlSection/ListView/NodeItem.tsx
- client/src/konva_mindmap/components/EditableTextInput.tsx
- input 활성화 시 요소 전체선택 ( 수정 바로 할 수 있도록 )
> [Feature-input-fe] input 활성화 시 요소 전체선택 ( 수정 바로 할 수 있도록 )

- client/src/components/Modal/ShareModal.tsx
> [Feature-input-refactor-fe] 창 클릭시 복사 가능하도록 수정
